//! Store layer for the `stored_files` table (§8 of 0001_init.sql).
//!
//! OpenAI-style file handles: the PK is a TEXT id (`file_<hex>`) generated by the caller. The
//! bytes live on disk under `~/.writ/files` (age-encrypted); this row is metadata only. Supports
//! soft-delete (`deleted_at`) so handles can be retired without orphaning artifact references.
//!
//! Runtime-checked sqlx only (no compile-time macros). Errors map into `LocalError` via `?`.

use super::super::error::LocalResult;
use sqlx::sqlite::SqlitePool;

/// Max rows returned by an unbounded `list`.
const LIST_CAP: i64 = 500;

/// One row of the `stored_files` table. PK is TEXT.
#[derive(Debug, Clone, sqlx::FromRow, serde::Serialize, serde::Deserialize)]
pub struct StoredFile {
    /// TEXT handle, e.g. `file_ab12cd34`.
    pub id: String,
    pub storage_key: String,
    pub filename: String,
    pub content_type: String,
    pub size_bytes: i64,
    #[serde(default)]
    pub sha256: Option<String>,
    /// upload|api|workflow_output
    pub source: String,
    #[serde(default)]
    pub source_run_id: Option<i64>,
    #[serde(default)]
    pub purpose: Option<String>,
    pub status: String,
    #[serde(default)]
    pub expires_at: Option<String>,
    #[serde(default)]
    pub deleted_at: Option<String>,
    pub created_at: String,
    /// JSON-TEXT — callers serde it.
    #[serde(default)]
    pub meta: Option<String>,
}

/// Fields accepted on insert. `id` and `storage_key` are caller-generated.
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
pub struct NewStoredFile {
    /// TEXT handle, e.g. `file_<hex>` — caller-generated.
    pub id: String,
    pub storage_key: String,
    pub filename: String,
    /// Defaults to `application/octet-stream` when empty.
    #[serde(default)]
    pub content_type: Option<String>,
    /// Defaults to 0 when `None`.
    #[serde(default)]
    pub size_bytes: Option<i64>,
    #[serde(default)]
    pub sha256: Option<String>,
    /// Defaults to `upload` when empty.
    #[serde(default)]
    pub source: Option<String>,
    #[serde(default)]
    pub source_run_id: Option<i64>,
    #[serde(default)]
    pub purpose: Option<String>,
    /// Defaults to `ready` when empty.
    #[serde(default)]
    pub status: Option<String>,
    #[serde(default)]
    pub expires_at: Option<String>,
    #[serde(default)]
    pub meta: Option<String>,
}

/// Insert a file handle row, returning the full row. Fails on duplicate `id`.
pub async fn insert(pool: &SqlitePool, f: &NewStoredFile) -> LocalResult<StoredFile> {
    let row = sqlx::query_as::<_, StoredFile>(
        r#"
        INSERT INTO stored_files (
            id, storage_key, filename, content_type, size_bytes, sha256,
            source, source_run_id, purpose, status, expires_at, meta
        ) VALUES (
            ?1, ?2, ?3,
            COALESCE(?4, 'application/octet-stream'),
            COALESCE(?5, 0),
            ?6,
            COALESCE(?7, 'upload'),
            ?8, ?9,
            COALESCE(?10, 'ready'),
            ?11, ?12
        )
        RETURNING *
        "#,
    )
    .bind(&f.id)
    .bind(&f.storage_key)
    .bind(&f.filename)
    .bind(&f.content_type)
    .bind(f.size_bytes)
    .bind(&f.sha256)
    .bind(&f.source)
    .bind(f.source_run_id)
    .bind(&f.purpose)
    .bind(&f.status)
    .bind(&f.expires_at)
    .bind(&f.meta)
    .fetch_one(pool)
    .await?;
    tracing::info!(file_id = %row.id, filename = %row.filename, size_bytes = row.size_bytes, "stored file inserted");
    Ok(row)
}

/// Fetch one file by its TEXT handle. Returns soft-deleted rows too (caller decides).
pub async fn get_by_id(pool: &SqlitePool, id: &str) -> LocalResult<Option<StoredFile>> {
    let row = sqlx::query_as::<_, StoredFile>("SELECT * FROM stored_files WHERE id = ?1")
        .bind(id)
        .fetch_optional(pool)
        .await?;
    Ok(row)
}

/// Fetch one *live* (not soft-deleted) file by handle.
pub async fn get_active(pool: &SqlitePool, id: &str) -> LocalResult<Option<StoredFile>> {
    let row = sqlx::query_as::<_, StoredFile>(
        "SELECT * FROM stored_files WHERE id = ?1 AND deleted_at IS NULL",
    )
    .bind(id)
    .fetch_optional(pool)
    .await?;
    Ok(row)
}

/// List live files, newest-first, capped. Soft-deleted rows are excluded.
pub async fn list(pool: &SqlitePool, limit: Option<i64>) -> LocalResult<Vec<StoredFile>> {
    let lim = limit.unwrap_or(LIST_CAP).clamp(1, LIST_CAP);
    let rows = sqlx::query_as::<_, StoredFile>(
        "SELECT * FROM stored_files WHERE deleted_at IS NULL ORDER BY created_at DESC, id DESC LIMIT ?1",
    )
    .bind(lim)
    .fetch_all(pool)
    .await?;
    Ok(rows)
}

/// List live files filtered by `source` (upload|api|workflow_output), newest-first.
pub async fn list_by_source(
    pool: &SqlitePool,
    source: &str,
    limit: Option<i64>,
) -> LocalResult<Vec<StoredFile>> {
    let lim = limit.unwrap_or(LIST_CAP).clamp(1, LIST_CAP);
    let rows = sqlx::query_as::<_, StoredFile>(
        "SELECT * FROM stored_files WHERE source = ?1 AND deleted_at IS NULL ORDER BY created_at DESC, id DESC LIMIT ?2",
    )
    .bind(source)
    .bind(lim)
    .fetch_all(pool)
    .await?;
    Ok(rows)
}

/// Find a live file by content hash (dedup lookup). Returns the most recent match.
pub async fn get_by_sha256(pool: &SqlitePool, sha256: &str) -> LocalResult<Option<StoredFile>> {
    let row = sqlx::query_as::<_, StoredFile>(
        "SELECT * FROM stored_files WHERE sha256 = ?1 AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 1",
    )
    .bind(sha256)
    .fetch_optional(pool)
    .await?;
    Ok(row)
}

/// Update mutable metadata (status / purpose / expiry / size+hash after upload completes / meta).
/// `None` fields are left untouched. Returns the updated row, or `None` if id absent.
pub async fn update(
    pool: &SqlitePool,
    id: &str,
    status: Option<&str>,
    purpose: Option<&str>,
    size_bytes: Option<i64>,
    sha256: Option<&str>,
    expires_at: Option<&str>,
    meta: Option<&str>,
) -> LocalResult<Option<StoredFile>> {
    let row = sqlx::query_as::<_, StoredFile>(
        r#"
        UPDATE stored_files SET
            status     = COALESCE(?2, status),
            purpose    = COALESCE(?3, purpose),
            size_bytes = COALESCE(?4, size_bytes),
            sha256     = COALESCE(?5, sha256),
            expires_at = COALESCE(?6, expires_at),
            meta       = COALESCE(?7, meta)
        WHERE id = ?1
        RETURNING *
        "#,
    )
    .bind(id)
    .bind(status)
    .bind(purpose)
    .bind(size_bytes)
    .bind(sha256)
    .bind(expires_at)
    .bind(meta)
    .fetch_optional(pool)
    .await?;
    Ok(row)
}

/// Set `status` only (e.g. `ready` -> `error`). Returns true if a row was touched.
pub async fn set_status(pool: &SqlitePool, id: &str, status: &str) -> LocalResult<bool> {
    let res = sqlx::query("UPDATE stored_files SET status = ?2 WHERE id = ?1")
        .bind(id)
        .bind(status)
        .execute(pool)
        .await?;
    Ok(res.rows_affected() > 0)
}

/// Soft-delete: stamp `deleted_at` and mark status `deleted`. The on-disk bytes are reclaimed
/// separately by storage GC. Returns `true` if a live row was retired.
pub async fn soft_delete(pool: &SqlitePool, id: &str) -> LocalResult<bool> {
    let res = sqlx::query(
        r#"
        UPDATE stored_files SET
            deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ','now'),
            status     = 'deleted'
        WHERE id = ?1 AND deleted_at IS NULL
        "#,
    )
    .bind(id)
    .execute(pool)
    .await?;
    let removed = res.rows_affected() > 0;
    if removed {
        tracing::info!(file_id = %id, "stored file soft-deleted");
    }
    Ok(removed)
}

/// Hard-delete the row (use after storage GC has removed the bytes). Returns `true` if removed.
pub async fn delete(pool: &SqlitePool, id: &str) -> LocalResult<bool> {
    let res = sqlx::query("DELETE FROM stored_files WHERE id = ?1")
        .bind(id)
        .execute(pool)
        .await?;
    let removed = res.rows_affected() > 0;
    if removed {
        tracing::info!(file_id = %id, "stored file hard-deleted");
    }
    Ok(removed)
}

/// List soft-deleted or expired files that are candidates for storage GC, oldest-first, capped.
/// `now_rfc3339` is the comparison instant for `expires_at`.
pub async fn list_gc_candidates(
    pool: &SqlitePool,
    now_rfc3339: &str,
    limit: Option<i64>,
) -> LocalResult<Vec<StoredFile>> {
    let lim = limit.unwrap_or(LIST_CAP).clamp(1, LIST_CAP);
    let rows = sqlx::query_as::<_, StoredFile>(
        r#"
        SELECT * FROM stored_files
        WHERE deleted_at IS NOT NULL
           OR (expires_at IS NOT NULL AND expires_at <= ?1)
        ORDER BY created_at ASC, id ASC
        LIMIT ?2
        "#,
    )
    .bind(now_rfc3339)
    .bind(lim)
    .fetch_all(pool)
    .await?;
    Ok(rows)
}
